# docker-compose.env.yaml
# 本地测试环境搭建

networks:
  horizon-cloud-admin-net:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: horizon-cloud-admin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: horizon-cloud-admin-db
      TZ: Asia/Shanghai
    ports:
      - "3309:3306"
    privileged: true
    restart: always
    networks:
      - horizon-cloud-admin-net

  redis:
    image: redis:7.0
    container_name: horizon-cloud-admin-redis
    command: --requirepass 12345678  # 设置密码，需与配置文件一致
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    privileged: true
    restart: always
    networks:
      - horizon-cloud-admin-net